# Generated by Django 5.2.4 on 2026-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player2Effect',
            field=models.IntegerField(default=0),
        ),
    ]
